### ISSUE TITLE
You have wrong links in marketplace to your repository

### ISSUE THREAD

**Issue by kanlukasz** [gurumukhi/vscode-extension-line-count#2] opened 2020-01-29 17:38 UTC
![obraz](https://user-images.githubusercontent.com/30685349/73381712-7f9a5500-42c6-11ea-84a6-6ef2db918106.png)

**Comment by gurumukhi** [comment] 2020-07-09 15:16
Thanks for reporting, the issue is now fixed (https://marketplace.visualstudio.com/items?itemName=gurumukhi.selected-lines-count).

**Closed by gurumukhi** 2020-07-09 15:16 UTC
